name: Authorise against container registry 
description: login to ghcr.io
inputs: {}
outputs: {}
runs:
  using: 'composite'
  steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}