include:
  - project: "ExplorViz/code/deployment"
    file: ".gitlab-ci-explorviz-common.yml"

default:
  tags:
    - exec-docker
  image: ghcr.io/graalvm/graalvm-community:21
  cache: # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"

stages:
  - build
  - code-analysis
  - test
  - deploy:images

build:
  stage: build
  script: ./gradlew assemble
  artifacts:
    paths:
      - build

pmd:
  stage: code-analysis
  script: ./gradlew pmdMain
  artifacts:
    paths:
      - build

checkstyle:
  stage: code-analysis
  script: ./gradlew checkstyleMain
  artifacts:
    paths:
      - build

unit-test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build

integration-test:
  stage: test
  script:
    - ./gradlew integrationTest
  allow_failure: true
  artifacts:
    paths:
      - build

push-dockerhub-native-mr:
  extends: .build-and-deploy-quarkus-native
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    IMAGE_TAG: mr-${CI_MERGE_REQUEST_IID}-native

push-dockerhub-mr:
  extends: .build-and-deploy-quarkus-jvm
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    IMAGE_TAG: mr-${CI_MERGE_REQUEST_IID}-jvm
