image: openjdk:17-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle

stages:
  - build
  - code-analysis

build:
  stage: build
  tags:
    - exec-docker
  script: ./gradlew assemble
  artifacts:
    paths:
      - build

pmd:
  stage: code-analysis
  tags:
    - exec-docker
  script: ./gradlew pmdMain
  artifacts:
    paths:
      - build

checkstyle:
  stage: code-analysis
  tags:
    - exec-docker
  script: ./gradlew checkstyleMain
  artifacts:
    paths:
      - build
