name: install the quarkus-cli
description: installs java and quarkus via jbang
inputs:
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: Docker image tag
    required: true
outputs: {}
runs:
  using: 'composite'
  steps:
      - name: Set up graalvm
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: install quarkus-cli tool
        shell: sh
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio

          echo "$HOME/.jbang/bin:$PATH" >> $GITHUB_PATH
      - run: quarkus extension add container-image-docker
        shell: sh
      - run: quarkus extension add container-image-jib 
        shell: sh